### ISSUE TITLE
Can't recompile.

### ISSUE THREAD

**Issue by Blayung** [MCPHackers/RetroMCP-Java#105]
It worked just fine but it suddenly stopped. I use a compiled version of retro mcp from the [latest commit](https://github.com/MCPHackers/RetroMCP-Java/commit/6c3fd08a2231810e7ce809383d0ffb7a44096e70) (for [intellij support](https://github.com/MCPHackers/RetroMCP-Java/issues/103)).  
Basically, when I try to recompile, it throws such an error:
```
An exception has occurred in the compiler (1.8.0_392). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.ClassFormatError: Unknown constant tag 110 in class file com/sun/tools/javac/code/Scope
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:822)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.sun.tools.javac.main.JavaCompiler.<init>(JavaCompiler.java:348)
        at com.sun.tools.javac.main.JavaCompiler.instance(JavaCompiler.java:88)
        at com.sun.tools.javac.main.Main.compile(Main.java:485)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at org.mcphackers.mcp.tasks.TaskRecompile.recompile(TaskRecompile.java:150)
        at org.mcphackers.mcp.tasks.TaskRecompile.lambda$setStages$2(TaskRecompile.java:96)
        at org.mcphackers.mcp.tasks.TaskStaged$Stage.doTask(TaskStaged.java:77)
        at org.mcphackers.mcp.tasks.TaskStaged$Stage.access$200(TaskStaged.java:61)
        at org.mcphackers.mcp.tasks.TaskStaged.doTask(TaskStaged.java:36)
        at org.mcphackers.mcp.tasks.Task.performTask(Task.java:40)
        at org.mcphackers.mcp.MCP.lambda$performTask$0(MCP.java:114)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
        Suppressed: java.io.IOException: CRC error while extracting entry from JAR file
                at sun.misc.URLClassPath$JarLoader$2.getBytes(URLClassPath.java:1007)
                at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
```
I've got no idea what is causing it, could you guys help?

**Comment by Blayung** [comment]
The problem also occurs when decompiling the server. It probably does the recompilation process too.

**Comment by PhoenixVX** [comment]
Try re-setting up the version you're decompiling. There's a suppressed exception at the end (CRC error) which hints that one of the libraries or the minecraft JAR itself may be corrupt.

**Comment by Blayung** [comment]
I did that, but it still throws the same error. (when decompiling)

**Comment by PhoenixVX** [comment]
What version are you using and are you using a modified Minecraft JAR?

**Comment by Blayung** [comment]
Never mind, it works now.
