### ISSUE TITLE
Often `ZipException` while decompilation

### ISSUE THREAD

**Issue by ChefMC** [MCPHackers/RetroMCP-Java#112]
Some classes won't decompile and RMCP breaking decompilation with error:

```
java.util.zip.ZipException: duplicate entry: net/any/package/Example.class
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:233)
	at org.mcphackers.rdi.nio.ClassStorageWriter.write(ClassStorageWriter.java:57)
	at org.mcphackers.rdi.nio.RDInjector.write(RDInjector.java:71)
	at org.mcphackers.rdi.nio.RDInjector.write(RDInjector.java:75)
	at org.mcphackers.mcp.tasks.TaskDecompile.applyInjector(TaskDecompile.java:190)
	at org.mcphackers.mcp.tasks.TaskDecompile.lambda$setStages$1(TaskDecompile.java:72)
	at org.mcphackers.mcp.tasks.TaskDecompile$$Lambda$66/615932360.doTask(Unknown Source)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.doTask(TaskStaged.java:76)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.access$200(TaskStaged.java:60)
	at org.mcphackers.mcp.tasks.TaskStaged.doTask(TaskStaged.java:36)
	at org.mcphackers.mcp.tasks.Task.performTask(Task.java:65)
	at org.mcphackers.mcp.MCP.lambda$performTask$0(MCP.java:115)
	at org.mcphackers.mcp.MCP$$Lambda$61/632266499.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Class successfully exist in decompiled.jar, but further decompilation (of another classes) is stopped.

I tried to fix that this way (inside your `org.mcphackers.rdi.nio.ClassStorageWriter` class):
![image](https://github.com/MCPHackers/RetroMCP-Java/assets/3519015/c2eba461-8506-4c08-9744-ade377cd3cbf)
But I still getting the same error, like my fix doesn't exist at all.

**Comment by PhoenixVX** [comment]
Do you happen to have the JAR file that causes this?

**Comment by NDruce** [comment]
Not yet. I got this error:

```
java.util.zip.ZipException: duplicate entry: net/minecraft/src/RenderEntity.class
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:233)
	at org.mcphackers.rdi.nio.ClassStorageWriter.write(ClassStorageWriter.java:57)
	at org.mcphackers.rdi.nio.RDInjector.write(RDInjector.java:71)
	at org.mcphackers.rdi.nio.RDInjector.write(RDInjector.java:75)
	at org.mcphackers.mcp.tasks.TaskDecompile.applyInjector(TaskDecompile.java:190)
	at org.mcphackers.mcp.tasks.TaskDecompile.lambda$setStages$1(TaskDecompile.java:72)
	at org.mcphackers.mcp.tasks.TaskDecompile$$Lambda$64/555817820.doTask(Unknown Source)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.doTask(TaskStaged.java:76)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.access$200(TaskStaged.java:60)
	at org.mcphackers.mcp.tasks.TaskStaged.doTask(TaskStaged.java:36)
	at org.mcphackers.mcp.tasks.Task.performTask(Task.java:65)
	at org.mcphackers.mcp.MCP.lambda$performTask$0(MCP.java:115)
	at org.mcphackers.mcp.MCP$$Lambda$62/1529353516.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

For this class:

![image](https://github.com/user-attachments/assets/7e6bc286-45a9-4db7-b387-1e3c52cb8a4e)

**Comment by NDruce** [comment]
Probably found. "RenderEntity" class name already occupied by "mb.class" (`mb.class` - it's RenderEntity in mappings). So `mb.class` was decompiled as `RenderEntity.java` in sources, which means conflicting with `RenderEntity.class` (literally) which exist from any of mods

**Comment by Lassebq** [comment]
https://github.com/MCPHackers/RetroDebugInjector/commit/4430d7203db0f8ef08513dea08835deaa77a2d71

**Comment by PhoenixVX** [comment]
Closing this issue. The solution above works in general but isn't foolproof. For most users, this issue should be fixed.
