### ISSUE TITLE
The .dylib files in bootup don't work on Apple Silicon

### ISSUE THREAD

**Issue by amazondelivery** [MCPHackers/RetroMCP-Java#113]
`
> start client
16 achievements
151 recipes
Setting user: Player094, -
Exception in thread "Minecraft main thread" java.lang.UnsatisfiedLinkError: /Users/[user_name]/Downloads/retromcp/libraries/natives/liblwjgl.dylib: dlopen(/Users/[user_name]/Downloads/retromcp/libraries/natives/liblwjgl.dylib, 0x0001): tried: '/Users/[user_name]/Downloads/retromcp/libraries/natives/liblwjgl.dylib' (fat file, but missing compatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/[user_name]/Downloads/retromcp/libraries/natives/liblwjgl.dylib' (no such file), '/Users/[user_name]/Downloads/retromcp/libraries/natives/liblwjgl.dylib' (fat file, but missing compatible architecture (have 'x86_64', need 'arm64'))
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:844)
	at java.lang.System.loadLibrary(System.java:1136)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:197)
	at net.minecraft.client.Minecraft.run(Minecraft.java:490)
	at java.lang.Thread.run(Thread.java:750)
[INFO]: Finished successfully!`

The .dylib files aren't able to be run on Apple Silicon. Is there any way to fix this?

**Comment by PhoenixVX** [comment]
You will need to replace the .dylib files manually with a copy built for ARM64. You can find a copy of those online or build it yourself from https://github.com/babric/lwjgl.

RetroMCP-Java doesn't currently ship ARM 64 builds as it would require determining the current JVM architecture (I.E. whether to use ARM 64 or x86_64 dylibs) since we can't rely on the fact that an ARM 64 processor runs an ARM 64 version of Java.

**Comment by amazondelivery** [comment]
Thanks man :)

**Comment by PhoenixVX** [comment]
That isn't to say doing this isn't necessarily planned or not. I just don't have the hardware to test nor to verify it even works on x86_64 so yeah... fun.
