### ISSUE TITLE
Setup for a1.0.16_02 giving me an error and won't work

### ISSUE THREAD

**Issue by bruh2899** [MCPHackers/RetroMCP-Java#114]
I keep getting this error here it is:
java.nio.file.AccessDeniedException: C:\WINDOWS\system32\jars
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at org.mcphackers.mcp.tools.FileUtil.createDirectories(FileUtil.java:47)
	at org.mcphackers.mcp.tasks.TaskSetup.doTask(TaskSetup.java:37)
	at org.mcphackers.mcp.tasks.Task.performTask(Task.java:65)
	at org.mcphackers.mcp.MCP.lambda$performTask$0(MCP.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
And I have no idea on how to fix it.
also it isn't just for this version it's for all versions

**Comment by mudkipdev** [comment]
You launched RetroMCP wrong, probably by double-clicking in explorer or something. Try running it from the command prompt with Java 8.

**Comment by bruh2899** [comment]
I don't know how because I am not that good with java.

**Comment by bruh2899** [comment]
thanks
