### ISSUE TITLE
Building an alpha 1.0.1_01 version does not work

### ISSUE THREAD

**Issue by Melthen-bor** [MCPHackers/RetroMCP-Java#122]
If try to build it, I even tried including ASM 9.6 in the lib folder and I have tried updating ASM in the libraries folder in which MCPhackers was. I am using the GUI version v1.0 . I have jdk 17, jdk 20, and jdk 21 installed if that might be the issue but it probably is not considering I set the JAVA_HOME option to jdk 17(yes the path to jdk 17) but it just gives me this error:
java.lang.IllegalArgumentException: Unsupported class file major version 65
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.mcphackers.mcp.tasks.TaskReobfuscate.lambda$reobfuscate$1(TaskReobfuscate.java:68)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.mcphackers.mcp.tasks.TaskReobfuscate.reobfuscate(TaskReobfuscate.java:64)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.doTask(TaskStaged.java:76)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.access$200(TaskStaged.java:60)
	at org.mcphackers.mcp.tasks.TaskStaged.doTask(TaskStaged.java:36)
	at org.mcphackers.mcp.tasks.TaskBuild.lambda$setStages$0(TaskBuild.java:30)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.doTask(TaskStaged.java:76)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.access$200(TaskStaged.java:60)
	at org.mcphackers.mcp.tasks.TaskStaged.doTask(TaskStaged.java:36)
	at org.mcphackers.mcp.tasks.Task.performTask(Task.java:65)
	at org.mcphackers.mcp.MCP.lambda$performTask$0(MCP.java:115)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by PhoenixVX** [comment]
RMCP ignores the JAVA_HOME environment variable/option. Whatever JVM is used to launch RMCP is what is used instead.

You will need to launch RMCP with a different JDK (particularly 8), update the ASM library bundled in RMCP itself, or fix your registry path to point to the correct JDK.

Aside from that, please use the Discussions tab instead of the Issues tab as this is for issues with RMCP itself, not for issues with how you use RMCP.

**Comment by Melthen-bor** [comment]
ok
