### ISSUE TITLE
Cannot launch, recompile etc...

### ISSUE THREAD

**Issue by Bagietas** [MCPHackers/RetroMCP-Java#128]
Hey, I've wanted to use RetroMCP but.... when recompiling or launching I get
`exception in thread "main" java.lang.ExceptionInInitializerError
	at org.mcphackers.launchwrapper.Launch.<clinit>(Launch.java:11)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)
	at org.mcphackers.launchwrapper.loader.LaunchClassLoader.getSystemClass(LaunchClassLoader.java:277)
	at org.mcphackers.launchwrapper.loader.LaunchClassLoader.getSupportedClassVersion(LaunchClassLoader.java:287)
	at org.mcphackers.launchwrapper.loader.LaunchClassLoader.<clinit>(LaunchClassLoader.java:34)
	... 1 more`
	
I've got JAVA_HOME and path pointing to Java JDK 1.8

**Comment by PhoenixVX** [comment]
RetroMCP uses the JDK it is launched with, not JAVA_HOME or PATH. 

Open it from a command line/terminal or correct your registry as it's using the wrong values.

This is explained in the wiki.
