### ISSUE TITLE
Unable to get version  list

### ISSUE THREAD

**Issue by ghost** [MCPHackers/RetroMCP-Java#147]
Version: [RetroMCP-Java 1.0](https://github.com/MCPHackers/RetroMCP-Java/releases/tag/v1.0)

JDK: zulu8.80.0.17-ca-jdk8.0.422-win_x64

```java
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:293)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:465)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:560)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1572)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.mcphackers.mcp.tools.versions.VersionParser.getJson(VersionParser.java:154)
	at org.mcphackers.mcp.tools.versions.VersionParser.<init>(VersionParser.java:31)
	at org.mcphackers.mcp.tools.versions.VersionParser.<clinit>(VersionParser.java:23)
	at org.mcphackers.mcp.gui.MCPFrame.lambda$reloadVersionList$1(MCPFrame.java:158)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by PhoenixVX** [comment]
Does this happen consistently? This simply looks like a slow internet connection to me.
