### ISSUE TITLE
`NullPointerException` if you run `help` for a command with arguments

### ISSUE THREAD

**Issue by TheAwesome98-Real** [MCPHackers/RetroMCP-Java#155]
if you run `help` for a command with arguments, like `build` or `decompile`, this happens:
```console
> help build
 - build        Build the jar or a zip with modified classes
Optional parameters:
Exception in thread "main" java.lang.NullPointerException
        at org.mcphackers.mcp.main.MainCLI.<init>(MainCLI.java:147)
        at org.mcphackers.mcp.main.MainCLI.main(MainCLI.java:60)
```

**Comment by PhoenixVX** [comment]
This is fixed in latest commits. It is not available in a release yet.
