### ISSUE TITLE
Unable to run on Multimc

### ISSUE THREAD

**Issue by mikethenerd1** [MCPHackers/RetroMCP-Java#157]
When I try to put my mod in multimc through replacing the jar with my own and it puts out this error 

```
Could not set base folder. Failed to find/access Minecraft main class:
java.lang.ClassNotFoundException: net.minecraft.client.d
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.legacyLaunch(OneSixLauncher.java:117)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:273)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
``` 
how am I supposed to run this on other programs? I'm moding inf20100630-2 and replacing minecraft.jar for inf20100618. I'm using Java 8 for both recompiling and running.

**Comment by PhoenixVX** [comment]
Use Alpha 1.0.4 as the base version.

The main class changed after Infdev 20100624 and Alpha 1.0.4 uses the same main class as those later Infdev versions.

**Comment by mikethenerd1** [comment]
Doing that just gave this error 
```
Exception in thread "Minecraft main thread" java.lang.NoClassDefFoundError: net/minecraft/src/Minecraft$SyntheticClass_1
	at aw.a(aw.java:225)
	at aw.b(aw.java:216)
	at aw.a(aw.java:127)
	at aw.run(aw.java:331)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.src.Minecraft$SyntheticClass_1
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 5 more
```

**Comment by PhoenixVX** [comment]
Are you using v1.0-pre3?

If so, I believe there is an issue with that version not marking synthetic classes for reobfuscation. Either use a full build of your mod or use v1.0.

**Comment by sech1p** [comment]
Hello! I have similar problem and I was not able run Minecraft Indev 20100110 due to error `IllegalArgumentException: input == null`. What I can do? I used `reobfuscated.jar` file as replacement of Minecraft jar.

**Comment by PhoenixVX** [comment]
You should not be using that JAR file as a replacement. Run the build task and it will generate a ZIP file containing your changes.

The issue here is actually because reobfuscated.jar does not contain resources and Minecraft throws an exception when certain resources cannot be found.

**Comment by PhoenixVX** [comment]
Is this still an issue?

**Comment by PhoenixVX** [comment]
Closing issue as inactive. Please reopen if the issue persists.
