### ISSUE TITLE
Cannot run my build from launcher.

### ISSUE THREAD

**Issue by km-khonsu** [MCPHackers/RetroMCP-Java#22]
I've built my client using the UI and wanted to run it from my launcher but it didn't work.

**Comment by km-khonsu** [comment]
Here's the log:
```
Picked up _JAVA_OPTIONS: 
Jun 27, 2022 7:33:35 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Using tweak class name net.minecraft.launchwrapper.VanillaTweaker
Jun 27, 2022 7:33:35 PM net.minecraft.launchwrapper.LogWrapper log
SEVERE: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:179)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:53)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:171)
	... 6 more
```

**Comment by Lassebq** [comment]
Otherwise include the zip to classpath or replace original jar contents with zip contents and delete meta-inf
