### ISSUE TITLE
No lwjgl64 in java.library.path in IntelliJ by default

### ISSUE THREAD

**Issue by SolDev69** [MCPHackers/RetroMCP-Java#26]
I setup a workspace to attempt 64bitification of a1.0.3 and decompiled the game, tried opening it after adding teleportation and got this lovely error. Apparently, libraries in the default IntelliJ workspace have *still* not been moved over. I'll try submitting a pr if I can navigate RMCPJ's code at all now.
```
Exception in thread "Minecraft main thread" java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:87)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:137)
	at net.minecraft.src.Minecraft.startGame(Minecraft.java:96)
	at net.minecraft.src.Minecraft.run(Minecraft.java:329)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by SolDev69** [comment]
Update: apparently it has been fixed in the latest commit which I will just use the jar from.
