### ISSUE TITLE
Current Versions is empty

### ISSUE THREAD

**Issue by TheAwesome98-Real** [MCPHackers/RetroMCP-Java#31]
this exception might be related:

```
org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:521)
	at org.json.JSONArray.<init>(JSONArray.java:109)
	at org.json.JSONArray.<init>(JSONArray.java:162)
	at org.mcphackers.mcp.tools.Util.parseJSONArray(Util.java:195)
	at org.mcphackers.mcp.tools.versions.VersionParser.getJson(VersionParser.java:156)
	at org.mcphackers.mcp.tools.versions.VersionParser.<init>(VersionParser.java:31)
	at org.mcphackers.mcp.tools.versions.VersionParser.<clinit>(VersionParser.java:24)
	at org.mcphackers.mcp.main.MainCLI.<init>(MainCLI.java:71)
	at org.mcphackers.mcp.main.MainCLI.main(MainCLI.java:59)
```

happens on both gui and cli jar but i prefer cli

**Comment by Lassebq** [comment]
Latest commits are not intended for public use yet, they are dependent on the new versions.json structure

**Comment by TheAwesome98-Real** [comment]
ah, i just `git clone`d out of habit. how can i find public use versions?

**Comment by Lassebq** [comment]
Get a pre-built jar from github releases, v1.0-pre1

**Comment by TheAwesome98-Real** [comment]
ok, thanks
