### ISSUE TITLE
Can't find where it builds my jar?

### ISSUE THREAD

**Issue by FHFHFHFJFHDHF** [MCPHackers/RetroMCP-Java#33]
I need some help, EVERY TIME I EXPORT I can't find anything new in the folders. Where does retromcp build?

**Comment by Lassebq** [comment]
What do you mean by export? Are you running the build task?

**Comment by FHFHFHFJFHDHF** [comment]
Yes, I mean that.

**Comment by Lassebq** [comment]
Should be `build` folder in the working directory. (It's the directory you ran it in if you never changed it)

**Comment by FHFHFHFJFHDHF** [comment]
I have no build folder?

**Comment by FHFHFHFJFHDHF** [comment]
![image](https://user-images.githubusercontent.com/69987806/195434915-cdc863de-5ffc-4c30-bba3-1c77b3bc606e.png)

**Comment by Lassebq** [comment]
You probably had errors when building it then, or you didn't run it at all?

**Comment by FHFHFHFJFHDHF** [comment]
I ran it, and also there was errors
`ava.lang.IllegalArgumentException: Unsupported class file major version 63
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.mcphackers.mcp.tools.mappings.MappingUtil$1.visitFile(MappingUtil.java:104)
	at org.mcphackers.mcp.tools.mappings.MappingUtil$1.visitFile(MappingUtil.java:63)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at org.mcphackers.mcp.tools.mappings.MappingUtil.modifyMappings(MappingUtil.java:63)
	at org.mcphackers.mcp.tools.mappings.MappingUtil.modifyClasses(MappingUtil.java:47)
	at org.mcphackers.mcp.tasks.TaskReobfuscate.doTask(TaskReobfuscate.java:65)
	at org.mcphackers.mcp.tasks.TaskBuild.doTask(TaskBuild.java:34)
	at org.mcphackers.mcp.tasks.Task.performTask(Task.java:56)
	at org.mcphackers.mcp.MCP.lambda$performTask$0(MCP.java:84)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
`

**Comment by Lassebq** [comment]
Use java 8

**Comment by Lassebq** [comment]
You'd have to re-decompile though and apply changes again if you made any, otherwise if you attempt old workspace all files will be considered as modified
