### ISSUE TITLE
Advast thinks it a virus

### ISSUE THREAD

**Issue by Vincent392** [MCPHackers/RetroMCP-Java#36]
uhh yeah idk what but it happens on 1.0RC3
screenshot:
![image](https://user-images.githubusercontent.com/90470156/200354644-72f9d39f-b9bb-4cbd-8ff9-064afb2af28e.png)
log:
Nothing to clear!
java.io.FileNotFoundException: C:\Users\Administrator\Desktop\1.1.1x Deobfustcate B1.8.1\1.1.1x_21 1.0 CR4\conf\conf.zip (Access is denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at org.mcphackers.mcp.tools.FileUtil.downloadFile(FileUtil.java:103)
	at org.mcphackers.mcp.tasks.TaskSetup.doTask(TaskSetup.java:55)
	at org.mcphackers.mcp.tasks.Task.performTask(Task.java:58)
	at org.mcphackers.mcp.MCP.lambda$performTask$0(MCP.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
plz fix for 1.0RC4

**Comment by Geolykt** [comment]
User error.
You need to whitelist read/writes for RMCP in order for it to be able to function like you want.

**Comment by Vincent392** [comment]
> User error. You need to whitelist read/writes for RMCP in order for it to be able to function like you want.

ok mvm would be nice if it did it automatically.

**Comment by Vincent392** [comment]
and also there is a bug that sets the default workspace to system 32 on windows.. (OH GOD)

**Comment by Lassebq** [comment]
You antivirus is denying write access, please fix it on your side.
Not related to RMCP itself, therefore closing issue

**Comment by Lassebq** [comment]
> and also there is a bug that sets the default workspace to system 32 on windows.. (OH GOD)

Yeah, that's know. Don't use File -> Open with, either run it with a command line or the default file assosiation

**Comment by Lassebq** [comment]
Doesn't sound like RetroMCP would cause that, again

**Comment by Vincent392** [comment]
> > and also there is a bug that sets the default workspace to system 32 on windows.. (OH GOD)
> 
> Yeah, that's know. Don't use File -> Open with, either run it with a command line or the default file assosiation

yeah just add into the JVM Arguments for the GUI launch

**Comment by Vincent392** [comment]
i can say this though the GUI Is waayyyy better then The command prompt.
