### ISSUE TITLE
Error when Reobfuscating and Building Classic 0.0.11a

### ISSUE THREAD

**Issue by xX420MCplayerXx** [MCPHackers/RetroMCP-Java#49]
I cannot reobfuscate or build Classic 0.0.11a, I just get errors.
Errors when Reobfuscating:
"java.lang.NullPointerException: Cannot read field "classes" because "mappings" is null
	at org.mcphackers.mcp.tasks.TaskReobfuscate.reobfuscate(TaskReobfuscate.java:86)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.doTask(TaskStaged.java:76)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.access$200(TaskStaged.java:60)
	at org.mcphackers.mcp.tasks.TaskStaged.doTask(TaskStaged.java:36)
	at org.mcphackers.mcp.tasks.Task.performTask(Task.java:65)
	at org.mcphackers.mcp.MCP.lambda$performTask$0(MCP.java:115)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)"
Errors when Building:
"java.lang.NullPointerException: Cannot read field "classes" because "mappings" is null
	at org.mcphackers.mcp.tasks.TaskReobfuscate.reobfuscate(TaskReobfuscate.java:86)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.doTask(TaskStaged.java:76)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.access$200(TaskStaged.java:60)
	at org.mcphackers.mcp.tasks.TaskStaged.doTask(TaskStaged.java:36)
	at org.mcphackers.mcp.tasks.TaskBuild.lambda$setStages$0(TaskBuild.java:30)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.doTask(TaskStaged.java:76)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.access$200(TaskStaged.java:60)
	at org.mcphackers.mcp.tasks.TaskStaged.doTask(TaskStaged.java:36)
	at org.mcphackers.mcp.tasks.Task.performTask(Task.java:65)
	at org.mcphackers.mcp.MCP.lambda$performTask$0(MCP.java:115)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)"
I have no clue how to fix this.

**Comment by PhoenixVX** [comment]
This issue has been fixed in commit https://github.com/MCPHackers/RetroMCP-Java/commit/66a03977129d1ff0511ff1bdb275d86a70ef6abf. If the issue still occurs, please reopen this issue.
