### ISSUE TITLE
Decompiling r1.1 with Modloader/ModloaderMP/Audiomod fails

### ISSUE THREAD

**Issue by mojontwins** [MCPHackers/RetroMCP-Java#62]
Decompiling a r1.1 minecraft.jar Client patched with Modloader/ModloaderMP/Audiomod fails at the beginning of the process with this error:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 35
	at java.lang.String.codePointAt(String.java:687)
	at org.mcphackers.rdi.injector.remapper.Remapper.remapSignature(Remapper.java:735)
	at org.mcphackers.rdi.injector.remapper.Remapper.remapSignature(Remapper.java:717)
	at org.mcphackers.rdi.injector.remapper.Remapper.remapField(Remapper.java:455)
	at org.mcphackers.rdi.injector.remapper.Remapper.process(Remapper.java:231)
	at org.mcphackers.rdi.nio.RDInjector.lambda$applyMappings$0(RDInjector.java:94)
	at org.mcphackers.rdi.nio.RDInjector.transform(RDInjector.java:80)
	at org.mcphackers.mcp.tasks.TaskDecompile.applyInjector(TaskDecompile.java:189)
	at org.mcphackers.mcp.tasks.TaskDecompile.lambda$setStages$1(TaskDecompile.java:72)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.doTask(TaskStaged.java:76)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.access$200(TaskStaged.java:60)
	at org.mcphackers.mcp.tasks.TaskStaged.doTask(TaskStaged.java:36)
	at org.mcphackers.mcp.tasks.Task.performTask(Task.java:65)
	at org.mcphackers.mcp.MCP.lambda$performTask$0(MCP.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

Patched JAR can be downloaded here: https://github.com/mojontwins/MC_Mods/raw/master/misc/minecraft.jar

**Comment by CodeKid0** [comment]
What RetroMCP version and java version are you using?

**Comment by mojontwins** [comment]
Sorry - Audiomod / Modloader / ModloaderMP decompile just fine. The error happens when you add the Twilight Forest (1.6.2 for r1.1) to the mix. 
Maybe I'm not doing it the right way? I'm just adding TF to the main JAR even thought it is a modloader mod.

**Comment by CodeKid0** [comment]
You can open up the mod .jar in Recaf or Enigma and apply the mappings, the mod source should be readable then.

**Comment by Lassebq** [comment]
Should be fixed with https://github.com/MCPHackers/RetroDebugInjector/commit/c9cbed52c8d2b35e9f7942df44b6842a6f7e94d5
Need to make a build of RMCP which features that commit though

**Comment by PhoenixVX** [comment]
Updated build of RDI can be found with RMCP https://github.com/MCPHackers/RetroMCP-Java/commit/414c0fe9bd7ddbd450ad7403363e69a1ee0ddb08.

Will be closing this now, it isn't yet published into a release as 1.1 isn't ready yet.
