### ISSUE TITLE
Cannot recompile: java.lang.RuntimeException: Could not find compiling API

### ISSUE THREAD

**Issue by LukesOffline** [MCPHackers/RetroMCP-Java#70]
I have the error:
`java.lang.RuntimeException: Could not find compiling API
	at org.mcphackers.mcp.tasks.TaskRecompile.setStages(TaskRecompile.java:47)
	at org.mcphackers.mcp.tasks.TaskStaged.doTask(TaskStaged.java:32)
	at org.mcphackers.mcp.tasks.Task.performTask(Task.java:65)
	at org.mcphackers.mcp.MCP.lambda$performTask$0(MCP.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`
This makes me unable to recompile RetroMCP.

**Comment by LukesOffline** [comment]
> Are you using a JRE instead of a JDK?

I downloaded JDK 8 from the OpenJDK website just beforehand because I found I hadn't had a version of JDK 8, unsure if I install it correctly.
