### ISSUE TITLE
Error when trying to recompile and build alpha 1.0.16_02

### ISSUE THREAD

**Issue by GalaxyModzYT** [MCPHackers/RetroMCP-Java#71]
I'm getting an error when I try recompiling alpha 1.0.16_02, I tried using the same jdk version that a1.0.16_02 uses and jdk 8 and they both didn't work.

This pops up when I try to recompile:
java.lang.RuntimeException: Could not find compiling API
	at org.mcphackers.mcp.tasks.TaskRecompile.setStages(TaskRecompile.java:47)
	at org.mcphackers.mcp.tasks.TaskStaged.doTask(TaskStaged.java:32)
	at org.mcphackers.mcp.tasks.Task.performTask(Task.java:65)
	at org.mcphackers.mcp.MCP.lambda$performTask$0(MCP.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

and this pops up after I try to build the game:
java.io.IOException: server classes not found!
	at org.mcphackers.mcp.tasks.TaskUpdateMD5.updateMD5(TaskUpdateMD5.java:64)
	at org.mcphackers.mcp.tasks.TaskReobfuscate.lambda$setStages$0(TaskReobfuscate.java:43)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.doTask(TaskStaged.java:76)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.access$200(TaskStaged.java:60)
	at org.mcphackers.mcp.tasks.TaskStaged.doTask(TaskStaged.java:36)
	at org.mcphackers.mcp.tasks.TaskBuild.lambda$setStages$0(TaskBuild.java:30)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.doTask(TaskStaged.java:76)
	at org.mcphackers.mcp.tasks.TaskStaged$Stage.access$200(TaskStaged.java:60)
	at org.mcphackers.mcp.tasks.TaskStaged.doTask(TaskStaged.java:36)
	at org.mcphackers.mcp.tasks.Task.performTask(Task.java:65)
	at org.mcphackers.mcp.MCP.lambda$performTask$0(MCP.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by PhoenixVX** [comment]
Issue has already been reported.

#66
