### ISSUE TITLE
Cant run any version of minecraft

### ISSUE THREAD

**Issue by goog00goog** [MCPHackers/RetroMCP-Java#74]
i get this error 
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.mcphackers.launchwrapper.Launch.<clinit>(Launch.java:11)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 64
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)
	at org.mcphackers.launchwrapper.loader.LaunchClassLoader.getSystemClass(LaunchClassLoader.java:277)
	at org.mcphackers.launchwrapper.loader.LaunchClassLoader.getSupportedClassVersion(LaunchClassLoader.java:287)
	at org.mcphackers.launchwrapper.loader.LaunchClassLoader.<clinit>(LaunchClassLoader.java:34)
	... 1 more

```

**Comment by PhoenixVX** [comment]
Use Java 8 for compiling and running. It says this in the README. Do NOT use Java 20. It won't work.
