### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Bandu42794** [MCPHackers/RetroMCP-Java#96]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.mcphackers.launchwrapper.Launch.<clinit>(Launch.java:11)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)
	at org.mcphackers.launchwrapper.loader.LaunchClassLoader.getSystemClass(LaunchClassLoader.java:277)
	at org.mcphackers.launchwrapper.loader.LaunchClassLoader.getSupportedClassVersion(LaunchClassLoader.java:287)
	at org.mcphackers.launchwrapper.loader.LaunchClassLoader.<clinit>(LaunchClassLoader.java:34)
	... 1 more
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.mcphackers.launchwrapper.Launch.<clinit>(Launch.java:11)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)
	at org.mcphackers.launchwrapper.loader.LaunchClassLoader.getSystemClass(LaunchClassLoader.java:277)
	at org.mcphackers.launchwrapper.loader.LaunchClassLoader.getSupportedClassVersion(LaunchClassLoader.java:287)
	at org.mcphackers.launchwrapper.loader.LaunchClassLoader.<clinit>(LaunchClassLoader.java:34)
	... 1 more
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.mcphackers.launchwrapper.Launch.<clinit>(Launch.java:11)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)
	at org.mcphackers.launchwrapper.loader.LaunchClassLoader.getSystemClass(LaunchClassLoader.java:277)
	at org.mcphackers.launchwrapper.loader.LaunchClassLoader.getSupportedClassVersion(LaunchClassLoader.java:287)
	at org.mcphackers.launchwrapper.loader.LaunchClassLoader.<clinit>(LaunchClassLoader.java:34)
	... 1 more

what does this mean

**Comment by PhoenixVX** [comment]
Do not use Java 21. Use Java 8.

**Comment by KoshakMineDEV** [comment]
Do not use Java 8. Update project to newer java version:)

**Comment by GameHerobrine** [comment]
> Do not use Java 8. Update project to newer java version:)

use java 6 =>

**Comment by PhoenixVX** [comment]
Do not use Java 6. RMCP supports Java 8+. Latest RMCP commits have updated ASM which works for Java 21.
Locking this conversation as off-topic.
