### ISSUE TITLE
this happen when launching retromcp.

### ISSUE THREAD

**Issue by J-K-Tech** [MCPHackers/RetroMCP-Java#97]
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.mcphackers.mcp.tools.versions.VersionParser.getJson(VersionParser.java:154)
	at org.mcphackers.mcp.tools.versions.VersionParser.<init>(VersionParser.java:31)
	at org.mcphackers.mcp.tools.versions.VersionParser.<clinit>(VersionParser.java:23)
	at org.mcphackers.mcp.gui.MCPFrame.lambda$reloadVersionList$1(MCPFrame.java:158)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by J-K-Tech** [comment]
edit: ok this is a problem on you guys side.
i looked in the source and it cant download from https://mcphackers.github.io/versionsV2/versions.json as this file is not on server anymore.

**Comment by PhoenixVX** [comment]
Are you using a proper Java distribution? The link is a redirect to https://mcphackers.org (which MCPHackers doesn't actually own directly).

**Comment by PhoenixVX** [comment]
It works fine on my side.

**Comment by J-K-Tech** [comment]
when i compile myself it works for some reason, both on 17 and 8

**Comment by PhoenixVX** [comment]
Closing issue as inactive.
